### PR TITLE
Issues 198 201 failing local tests

### LINKED ISSUE #198: failing `server=local` tests on Travis against master
From https://travis-ci.org/mozilla/fxa-js-client/jobs/126195384

> FAIL: #with redirectTo (14ms)
AssertionError: expected { Object (code, errno, ...) } to be falsy
    at assert.notOk (/home/travis/build/mozilla/fxa-js-client/node_modules/intern-geezer/assert.js:529:10)
    at onSettled (/home/travis/build/mozilla/fxa-js-client/components/p/p.js:357:9)
    at Object.flush [as _onImmediate] (/home/travis/build/mozilla/fxa-js-client/components/p/p.js:64:6)
    at processImmediate [as _immediateCallback] (timers.js:363:15)
fxa-auth-server.INFO: request.summary {"op":"request.summary","code":400,"errno":107,"rid":"1461785098098:testing-worker-linux-docker-fffc1007-3362-linux-12:3187:inj93pje:10023","path":"/v1/account/login","agent":"Mozilla/5.0 (Linux x64) node.js/0.10.44 v8/3.14.5.9","remoteAddressChain":["127.0.0.1"],"t":2,"uid":"00","service":"sync","redirectTo":"http://sync.firefox.com/after_reset","keys":"true","email":"test1461785098091@restmail.net"}
FAIL: #with resume (11ms)
AssertionError: expected { Object (code, errno, ...) } to be falsy
    at assert.notOk (/home/travis/build/mozilla/fxa-js-client/node_modules/intern-geezer/assert.js:529:10)
    at onSettled (/home/travis/build/mozilla/fxa-js-client/components/p/p.js:357:9)
    at Object.flush [as _onImmediate] (/home/travis/build/mozilla/fxa-js-client/components/p/p.js:64:6)
    at processImmediate [as _immediateCallback] (timers.js:363:15)

I believe this is due to sending the resume token and redirectTo to an auth server that does not yet support those fields. Those fields are added in https://github.com/mozilla/fxa-auth-server/pull/1232

Ref https://github.com/mozilla/fxa-js-client/pull/197

### LINKED ISSUE #201: /account/(login|create) no longer support device registration
Remove this code, fix the tests.

### PR DESCRIPTION
**Pull request by shane-tomlinson**
fixes #198 
fixes #201

### CODE REVIEW

**Comment by shane-tomlinson** [comment]
@vladikoff - r?

**Comment by vbudhram** [comment]
LGTM, didn't find references to device in signup/signin.

**Comment by vladikoff** [comment]
👍

**Comment by vladikoff** [comment]
Travis 📗

**Pull request merged**
