### PR TITLE
fix(client): throw harder on bad client init

### PR DESCRIPTION
**Pull request by vladikoff**
Fixes https://github.com/mozilla/fxa-js-client/issues/142
Fixes https://github.com/mozilla/fxa-js-client/issues/149

### CODE REVIEW

**Comment by vladikoff** [comment]
@shane-tomlinson @zaach r?

**Comment by vladikoff** [comment]
@shane-tomlinson @zaach r?

**Comment by vladikoff** [comment]
@shane-tomlinson @zaach r? :stuck_out_tongue_winking_eye:

**Comment by zaach** [comment]
Heh. :+1:

**Pull request merged**
