### PR TITLE
feat(client): signIn support signin confirmation

### PR DESCRIPTION
**Pull request by shane-tomlinson**
* signIn now accepts `redirectTo` and `resume` options.

Goes with https://github.com/mozilla/fxa-auth-server/pull/1275, https://github.com/mozilla/fxa-content-server/pull/3671

### CODE REVIEW

**Comment by shane-tomlinson** [comment]
@vbudhram - running `npm run test-local` with the auth server from mozilla/fxa-auth-server#1275, I see an unexpected error:

```
FAIL: #verifyEmailCheckStatus (48ms)
AssertionError: Email should be verified.
    at /Users/stomlinson/development/fxa-js-client/tests/lib/verifyCode.js:93:22
    at onSettled (/Users/stomlinson/development/fxa-js-client/components/p/p.js:357:9)
    at Immediate.flush [as _onImmediate] (/Users/stomlinson/development/fxa-js-client/components/p/p.js:64:6)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

Is this a problem with the js-client or the auth server?

**Comment by vbudhram** [comment]
Looks like this assertion is failing, https://github.com/mozilla/fxa-js-client/blob/master/tests/lib/verifyCode.js#L93, per comment, technically the email is verified, `result.emailVerified=true`, however session is not.

Does it make sense to update this assertion?

**Comment by shane-tomlinson** [comment]
> Looks like this assertion is failing, https://github.com/mozilla/fxa-js-client/blob/master/tests/lib/verifyCode.js#L93, per comment, technically the email is verified, result.emailVerified=true, however session is not.
>
> Does it make sense to update this assertion?

I think it probably does.

**Comment by vladikoff** [comment]
blocked by auth-server changes.....

**Comment by philbooth** [comment]
👍

**Pull request merged**
