### PR TITLE
feat(recovery): initial support for account recovery

### PR DESCRIPTION
**Pull request by vbudhram**
blocked by https://github.com/mozilla/fxa-auth-server/issues/2421

- [x] Add/cleanup comments
- [ ] ~~Add test cases for `RecoveryKey` util~~
- [ ] ~~Add test cases that use an explicit input vector per https://gist.github.com/rfk/0462fc6c81e43f2b9abbea41c479a784~~

### CODE REVIEW

**Comment by shane-tomlinson** [comment]
> feat(recovery): testing webpack 4

Love it. Can the update to webpack 4 be done outside of this PR?

**Comment by vbudhram** [comment]
> Can the update to webpack 4 be done outside of this PR?

Yup, it should be! I was running into some issues compiling this when I included the fxaCryptoRelier and wanted to try webpack 4. After speaking with vlad, he mentioned that it would make more sense to put in the content-server repo and have a similar setup as scoped keys.

**Comment by vbudhram** [comment]
@mozilla/fxa-devs Most of the logic in this PR was moved to https://github.com/mozilla/fxa-content-server/pull/6323. Hopefully it makes it easier to review.

**Comment by vbudhram** [comment]
@shane-tomlinson Thanks! I am going to wait to create a version since there might be tweak while building out https://github.com/mozilla/fxa-content-server/pull/6203.

**Pull request merged**
